spring:
  profiles:
    active: dev
    
---
# Ambiente dev
server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/account
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: 'info'
  info:
    env:
      enabled: true
info:
  app:
    version: 1.0.0
    name: Microservices Account
    description: Microservices related to account (clients with products)

---
# Ambiente prod
server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  profiles: prod
  data:
    mongodb:
      database: account
      uri: mongodb+srv://bootcamp:123@clusterbootcamp.uuzdqjo.mongodb.net/?retryWrites=true&w=majority
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://servicio-eureka-server:8761/eureka
    instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: 'info'
  info:
    env:
      enabled: true
info:
  app:
    version: 1.0.0
    name: Microservices Account
    description: Microservices related to account (clients with products)
